# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Browser\home1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.webView = QtWebKitWidgets.QWebView(self.tab)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.gridLayout_3.addWidget(self.webView, 3, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 5)
        self.btn1 = QtWidgets.QPushButton(self.tab)
        self.btn1.setAutoDefault(False)
        self.btn1.setFlat(True)
        self.btn1.setObjectName("btn1")
        self.gridLayout_3.addWidget(self.btn1, 2, 0, 1, 2)
        self.btnBMD = QtWidgets.QPushButton(self.tab)
        self.btnBMD.setStyleSheet(".QPushButton{background-image:url(\"E:/Browser/book.jpg\")}")
        self.btnBMD.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("book.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBMD.setIcon(icon)
        self.btnBMD.setIconSize(QtCore.QSize(24, 24))
        self.btnBMD.setFlat(True)
        self.btnBMD.setObjectName("btnBMD")
        self.gridLayout_3.addWidget(self.btnBMD, 0, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.btnBack = QtWidgets.QPushButton(self.tab)
        self.btnBack.setStyleSheet("")
        self.btnBack.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon1)
        self.btnBack.setFlat(True)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout_3.addWidget(self.btnBack, 0, 0, 1, 1)
        self.btnGo = QtWidgets.QPushButton(self.tab)
        self.btnGo.setObjectName("btnGo")
        self.gridLayout_3.addWidget(self.btnGo, 0, 3, 1, 1)
        self.btnForward = QtWidgets.QPushButton(self.tab)
        self.btnForward.setStyleSheet("")
        self.btnForward.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnForward.setIcon(icon2)
        self.btnForward.setFlat(True)
        self.btnForward.setObjectName("btnForward")
        self.gridLayout_3.addWidget(self.btnForward, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1249, 31))
        self.menubar.setObjectName("menubar")
        self.menuMENU = QtWidgets.QMenu(self.menubar)
        self.menuMENU.setObjectName("menuMENU")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_Tab = QtWidgets.QAction(MainWindow)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionBookMark = QtWidgets.QAction(MainWindow)
        self.actionBookMark.setObjectName("actionBookMark")
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setObjectName("actionHistory")
        self.menuMENU.addAction(self.actionNew_Tab)
        self.menuMENU.addAction(self.actionNew_Window)
        self.menuMENU.addAction(self.actionHistory)
        self.menuMENU.addAction(self.actionBookMark)
        self.menuMENU.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMENU.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BROWSER"))
        self.btn1.setText(_translate("MainWindow", "Google"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Type a URL "))
        self.btnGo.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.menuMENU.setTitle(_translate("MainWindow", "MENU"))
        self.actionNew_Tab.setText(_translate("MainWindow", "New Tab"))
        self.actionNew_Tab.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
        self.actionNew_Window.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionBookMark.setText(_translate("MainWindow", "BookMarks"))
        self.actionBookMark.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionHistory.setText(_translate("MainWindow", "History"))
        self.actionHistory.setShortcut(_translate("MainWindow", "Ctrl+H"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

